'use strict';
const $ = id => document.getElementById(id);
const state = {token:null,status:null,samples:{},sample:null,result:null,image:null,ocrLines:[],busy:false,selected:null,confirmed:new Set(),reminder:null,modelChosen:false};
let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),6500)}
function visible(id,yes){$(id).classList.toggle('hidden',!yes)}
function node(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el}
async function api(path,data){if(!state.token)await refreshStatus();const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Letterbox-Token':state.token},body:JSON.stringify({...data,publicConsent:!!$('public-consent')?.checked})});if(!response.ok){let message='The cloud request could not finish.';try{message=(await response.json()).error||message}catch{}throw new Error(message)}return path==='/api/calendar'?response.text():response.json()}
async function refreshStatus(){try{const response=await fetch('/api/status');if(!response.ok)throw new Error();state.status=await response.json();state.token=state.status.token;const models=state.status.models;const installed=models.length>0;$('engine-label').textContent=installed?'Test server ready':'Sample walkthrough available';$('settings-status').textContent=`${installed?'Test server connected.':'Hosted Gemma is not connected yet.'}  Photos are read on the Render cloud server. Model output is never treated as confirmed.`;for(const option of $('model-select').options)option.disabled=!models.includes(option.value);if(models.length&&!models.includes($('model-select').value))$('model-select').value=models.includes('gemma3:270m')?'gemma3:270m':models[0];if(!state.modelChosen&&models.length)$("model-select").value=models.includes("gemma3:1b")&&state.status.memory.available_gib>=1.8?"gemma3:1b":models[0];updateButton()}catch{$('engine-label').textContent='Cloud server is starting';$('settings-status').textContent='Cannot reach the cloud server. Please retry shortly while the cloud engine starts.'}}
function updateButton(){const text=$('letter-text').value.trim();$('analyze-button').disabled=state.busy||text.length<30;$('export-button').disabled=!state.result||state.busy;$('language-select').disabled=state.busy;$('clear-button').disabled=state.busy;$('sample-button').disabled=state.busy;$('file-input').disabled=state.busy;$('letter-text').disabled=state.busy;const ready=state.status?.models?.length;$('analyze-button').replaceChildren(document.createTextNode(state.busy?'Gemma is reading…':state.result?'Explain again':'Explain my letter'),node('span',null,'↗'));$('button-caption').textContent=state.sample&&!ready?'Example loaded. Hosted Gemma needs a configured connection.':!ready?'Try an example, or wait for the cloud connection.':'Server-side Gemma. Clear evidence. Your next step.'}
function switchTab(which){$('tab-upload').setAttribute('aria-selected',String(which==='upload'));$('tab-text').setAttribute('aria-selected',String(which==='text'));visible('upload-pane',which==='upload'&&!state.image&&!state.sample);visible('image-area',which==='upload'&&!!state.image);visible('text-pane',which==='text');visible('source-view',which==='upload'&&$('letter-text').value.length>0);if(which==='upload')renderSource();}
function clearResult(){state.result=null;state.selected=null;state.confirmed.clear();visible('result-area',false);visible('empty-state',true);$('result-label').textContent='IN YOUR WORDS';$('detail-list').replaceChildren();$('image-highlights').replaceChildren();$('source-text').replaceChildren(document.createTextNode($('letter-text').value));updateButton()}
function clearAll(){if(state.busy)return;window.speechSynthesis?.cancel();state.image=null;state.ocrLines=[];state.sample=null;state.reminder=null;$("reminder-quote").textContent="";$("reminder-title").value="";$("reminder-date").value="";$("confirm-date").checked=false;$('letter-text').value='';$('file-input').value='';$('original-image').removeAttribute('src');$('large-image').removeAttribute('src');$('source-label').textContent='ONE PAGE AT A TIME';clearResult();switchTab('upload');toast('Fresh start. Your letter and review have been cleared from this page.')}
function setBusy(busy,title='Finding a little clarity.',description='OCR runs on Render; selected source sentences go to Google-hosted Gemma.'){state.busy=busy;visible('loading-state',busy);visible('empty-state',!busy&&!state.result);visible('result-area',!busy&&!!state.result);$('loading-title').textContent=title;$('loading-description').textContent=description;$('load-step-one').classList.toggle('active',title.includes('Reading'));$('load-step-two').classList.toggle('active',!title.includes('Reading'));updateButton()}
async function upload(file){if(!$('public-consent').checked)return toast('Read the public test notice and confirm before uploading.');if(state.busy||!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type))return toast('Choose a JPG, PNG or WebP photo.');if(file.size>10*1024*1024)return toast('Please choose a photo smaller than 10 MB.');clearResult();state.sample=null;state.ocrLines=[];state.image=null;$('letter-text').value='';setBusy(true,'Reading, right here.','Tesseract OCR on the cloud server is reading your photo.');try{state.image=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});$('original-image').src=state.image;$('large-image').src=state.image;switchTab('upload');const result=await api('/api/ocr',{image:state.image});state.ocrLines=result.lines||[];$('letter-text').value=result.text;$('source-label').textContent='SERVER OCR · CHECK THE PHOTO';$('transcription-caption').textContent='TRANSCRIPTION · PLEASE CHECK';renderSource();visible('source-view',true);toast('Photo read on the test server. Check the transcription, then explain the letter.')}catch(error){toast(error.message);switchTab('text')}finally{setBusy(false);updateButton()}}
function renderSource(span=null){const text=$('letter-text').value;const container=$('source-text');container.replaceChildren();if(span&&span.start>=0&&span.end<=text.length){container.append(document.createTextNode(text.slice(0,span.start)),node('mark',null,text.slice(span.start,span.end)),document.createTextNode(text.slice(span.end)));container.scrollTop+=container.querySelector('mark').getBoundingClientRect().top-container.getBoundingClientRect().top-28}else container.textContent=text;renderImageHighlight(span)}
function renderImageHighlight(span){const container=$('image-highlights');container.replaceChildren();if(!span||!state.image||!state.ocrLines.length)return;const source=$('letter-text').value.slice(span.start,span.end).replace(/\s+/g,' ');for(const line of state.ocrLines){if(!source.includes(line.text.replace(/\s+/g,' ')))continue;const mark=node('div','ocr-highlight');mark.style.left=`${line.x*100}%`;mark.style.top=`${line.y*100}%`;mark.style.width=`${line.width*100}%`;mark.style.height=`${line.height*100}%`;container.append(mark)}}
function selectDetail(detail){state.selected=detail.id;for(const card of $('detail-list').children)card.classList.toggle('selected',card.dataset.id===detail.id);if(!detail.matched){toast('This quote was not found in the source text. Check the original; it cannot be highlighted.');return}switchTab('upload');renderSource(detail.span);visible('source-view',true);$('source-text').focus({preventScroll:true})}
function renderResult(result){state.result=result;state.selected=null;state.confirmed.clear();$('result-title').textContent=result.title||'Your letter, explained';$('result-label').textContent=result.mode==='sample'?'EXAMPLE WALKTHROUGH':'SERVER AI · REVIEW REQUIRED';const banner=$('result-banner');banner.classList.toggle('sample',result.mode==='sample');banner.textContent=result.mode==='sample'?'FICTIONAL SAMPLE · Curated explanation. No AI model was run.':`${result.model} · ${result.metrics.elapsed_seconds}s · ${result.metrics.matched}/${result.metrics.total} source quotes matched · Not independently verified`;$('detail-list').replaceChildren();if(!result.details.length){$('detail-list').append(node('p','fine-print','No usable details were returned. Review the original letter or try again.'))}
for(const detail of result.details){const card=node('article','detail-card');card.dataset.id=detail.id;const heading=node('div','detail-header');const kinds={date:['▦','Date stated'],amount:['£','Amount stated'],action:['↗','Requested action'],information:['◇','Information']};const [symbol,label]=kinds[detail.kind]||kinds.information;heading.append(node('span','detail-kind',`${symbol} ${label}`),node('span',`evidence-badge${detail.matched?'':' unmatched'}`,detail.matched?'✓ Quote matched':'! Needs checking'));card.append(heading,node('p',null,detail.explanation));const quote=node('button','quote-button');quote.append(document.createTextNode(`“${detail.quote||'No source quote provided.'}”`),node('span',null,detail.matched?'See in the original text ↗':'Source quote not found'));quote.addEventListener('click',()=>selectDetail(detail));card.append(quote);if(detail.source_only)card.append(node("p","source-only","Original excerpt shown; simplification unavailable or flagged."));for(const issue of detail.issues||[])card.append(node("p","detail-warning","Needs checking: "+issue));const footer=node('div','detail-footer');const review=node('label','review-check');const checkbox=node('input');checkbox.type='checkbox';checkbox.addEventListener('change',()=>{checkbox.checked?state.confirmed.add(detail.id):state.confirmed.delete(detail.id)});review.append(checkbox,document.createTextNode('I checked the original'));footer.append(review);if(detail.kind==='date'){const reminder=node('button','reminder-button','Create reminder ↗');reminder.disabled=!detail.matched||detail.supported===false;reminder.addEventListener('click',()=>openReminder(detail));footer.append(reminder)}card.append(footer);$('detail-list').append(card)}visible('result-area',true);visible('empty-state',false);visible('source-view',true);renderSource();updateButton()}
